name: hello_universe
description: This app shows Nasa Astrohomy Picture Of Day (APOD) using Nasa api.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  intl: ^0.17.0
  url_launcher: ^6.0.20

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/error.png
    - assets/no-results.png
    - assets/no-image.png
    - assets/placeholder.png
    - assets/splash.png
