name: hello_universe
description: This app shows Nasa Astrohomy Picture Of Day (APOD) using Nasa api.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  http: ^0.13.1
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.2.0

flutter:

