// Mocks generated by Mockito 5.4.6 from annotations
// in hello_universe/test/src/data/api_config_interceptor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:chopper/src/chain/chain.dart' as _i2;
import 'package:chopper/src/request.dart' as _i3;
import 'package:chopper/src/response.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [Chain].
///
/// See the documentation for Mockito's code generation for more information.
class MockChain<BodyType> extends _i1.Mock implements _i2.Chain<BodyType> {
  MockChain() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Request get request =>
      (super.noSuchMethod(
            Invocation.getter(#request),
            returnValue: _i4.dummyValue<_i3.Request>(
              this,
              Invocation.getter(#request),
            ),
          )
          as _i3.Request);

  @override
  _i5.FutureOr<_i6.Response<BodyType>> proceed(_i3.Request? request) =>
      (super.noSuchMethod(
            Invocation.method(#proceed, [request]),
            returnValue: _i5.Future<_i6.Response<BodyType>>.value(
              _i4.dummyValue<_i6.Response<BodyType>>(
                this,
                Invocation.method(#proceed, [request]),
              ),
            ),
          )
          as _i5.FutureOr<_i6.Response<BodyType>>);
}
