// Mocks generated by Mockito 5.4.6 from annotations
// in hello_universe/test/src/data/apods_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:built_collection/built_collection.dart' as _i3;
import 'package:chopper/chopper.dart' as _i5;
import 'package:hello_universe/src/data/apod_service.dart' as _i4;
import 'package:hello_universe/src/data/models/apod_dto.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeType_0 extends _i1.SmartFake implements Type {
  _FakeType_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApodDto_1 extends _i1.SmartFake implements _i2.ApodDto {
  _FakeApodDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBuiltList_2<E> extends _i1.SmartFake implements _i3.BuiltList<E> {
  _FakeBuiltList_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApodService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodService extends _i1.Mock implements _i4.ApodService {
  @override
  _i5.ChopperClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _i6.dummyValue<_i5.ChopperClient>(
              this,
              Invocation.getter(#client),
            ),
            returnValueForMissingStub: _i6.dummyValue<_i5.ChopperClient>(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i5.ChopperClient);

  @override
  Type get definitionType =>
      (super.noSuchMethod(
            Invocation.getter(#definitionType),
            returnValue: _FakeType_0(this, Invocation.getter(#definitionType)),
            returnValueForMissingStub: _FakeType_0(
              this,
              Invocation.getter(#definitionType),
            ),
          )
          as Type);

  @override
  set client(_i5.ChopperClient? value) => super.noSuchMethod(
    Invocation.setter(#client, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i2.ApodDto> fetchImage({required bool? includeThumbnails}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchImage, [], {
              #includeThumbnails: includeThumbnails,
            }),
            returnValue: _i7.Future<_i2.ApodDto>.value(
              _FakeApodDto_1(
                this,
                Invocation.method(#fetchImage, [], {
                  #includeThumbnails: includeThumbnails,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.ApodDto>.value(
              _FakeApodDto_1(
                this,
                Invocation.method(#fetchImage, [], {
                  #includeThumbnails: includeThumbnails,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.ApodDto>);

  @override
  _i7.Future<_i3.BuiltList<_i2.ApodDto>> fetchImageList({
    required String? startDate,
    required String? endDate,
    required bool? includeThumbnails,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchImageList, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includeThumbnails: includeThumbnails,
            }),
            returnValue: _i7.Future<_i3.BuiltList<_i2.ApodDto>>.value(
              _FakeBuiltList_2<_i2.ApodDto>(
                this,
                Invocation.method(#fetchImageList, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                  #includeThumbnails: includeThumbnails,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i3.BuiltList<_i2.ApodDto>>.value(
                  _FakeBuiltList_2<_i2.ApodDto>(
                    this,
                    Invocation.method(#fetchImageList, [], {
                      #startDate: startDate,
                      #endDate: endDate,
                      #includeThumbnails: includeThumbnails,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i3.BuiltList<_i2.ApodDto>>);
}
