// Mocks generated by Mockito 5.4.6 from annotations
// in hello_universe/test/src/router_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:hello_universe/src/domain/apods_error.dart' as _i5;
import 'package:hello_universe/src/presentation/apods_list/apods_list_cubit.dart'
    as _i2;
import 'package:hello_universe/src/presentation/apods_list/apods_list_data.dart'
    as _i4;
import 'package:hello_universe/src/utils/persistent_cubit_state.dart' as _i3;
import 'package:hello_universe/src/utils/uri_launcher/uri_launch_mode.dart'
    as _i10;
import 'package:hello_universe/src/utils/uri_launcher/uri_launcher.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApodsListCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodsListCubit extends _i1.Mock implements _i2.ApodsListCubit {
  @override
  _i3.PersistentCubitState<_i4.ApodsListData, _i5.ApodsError> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i6
                .dummyValue<
                  _i3.PersistentCubitState<_i4.ApodsListData, _i5.ApodsError>
                >(this, Invocation.getter(#state)),
            returnValueForMissingStub: _i6
                .dummyValue<
                  _i3.PersistentCubitState<_i4.ApodsListData, _i5.ApodsError>
                >(this, Invocation.getter(#state)),
          )
          as _i3.PersistentCubitState<_i4.ApodsListData, _i5.ApodsError>);

  @override
  _i7.Stream<_i3.PersistentCubitState<_i4.ApodsListData, _i5.ApodsError>>
  get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue:
                _i7.Stream<
                  _i3.PersistentCubitState<_i4.ApodsListData, _i5.ApodsError>
                >.empty(),
            returnValueForMissingStub:
                _i7.Stream<
                  _i3.PersistentCubitState<_i4.ApodsListData, _i5.ApodsError>
                >.empty(),
          )
          as _i7.Stream<
            _i3.PersistentCubitState<_i4.ApodsListData, _i5.ApodsError>
          >);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<void> fetchApods() =>
      (super.noSuchMethod(
            Invocation.method(#fetchApods, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void emit(
    _i3.PersistentCubitState<_i4.ApodsListData, _i5.ApodsError>? state,
  ) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(
    _i8.Change<_i3.PersistentCubitState<_i4.ApodsListData, _i5.ApodsError>>?
    change,
  ) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [UriLauncher].
///
/// See the documentation for Mockito's code generation for more information.
class MockUriLauncher extends _i1.Mock implements _i9.UriLauncher {
  @override
  _i7.Future<bool> launch(Uri? uri, {_i10.UriLaunchMode? mode}) =>
      (super.noSuchMethod(
            Invocation.method(#launch, [uri], {#mode: mode}),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}
