// Mocks generated by Mockito 5.4.6 from annotations
// in hello_universe/test/src/presentation/apods_list/apods_list_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:fpdart/fpdart.dart' as _i3;
import 'package:hello_universe/src/domain/entities/apod_page.dart' as _i5;
import 'package:hello_universe/src/domain/entities/apods_error.dart' as _i4;
import 'package:hello_universe/src/domain/entities/apods_page_key.dart' as _i6;
import 'package:hello_universe/src/domain/fetch_apods_use_case.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FetchApodsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchApodsUseCase extends _i1.Mock implements _i2.FetchApodsUseCase {
  @override
  _i3.TaskEither<_i4.ApodsError, _i5.ApodPage> execute({
    required _i6.ApodsPageKey? currentPageKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#currentPageKey: currentPageKey}),
            returnValue: _i7
                .dummyValue<_i3.TaskEither<_i4.ApodsError, _i5.ApodPage>>(
                  this,
                  Invocation.method(#execute, [], {
                    #currentPageKey: currentPageKey,
                  }),
                ),
            returnValueForMissingStub: _i7
                .dummyValue<_i3.TaskEither<_i4.ApodsError, _i5.ApodPage>>(
                  this,
                  Invocation.method(#execute, [], {
                    #currentPageKey: currentPageKey,
                  }),
                ),
          )
          as _i3.TaskEither<_i4.ApodsError, _i5.ApodPage>);
}
