// Mocks generated by Mockito 5.4.6 from annotations
// in hello_universe/test/src/presentation/apods_list/apods_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:flutter/widgets.dart' as _i4;
import 'package:flutter_bloc/flutter_bloc.dart' as _i14;
import 'package:go_router/src/configuration.dart' as _i3;
import 'package:go_router/src/delegate.dart' as _i5;
import 'package:go_router/src/information_provider.dart' as _i6;
import 'package:go_router/src/match.dart' as _i16;
import 'package:go_router/src/parser.dart' as _i7;
import 'package:go_router/src/router.dart' as _i15;
import 'package:go_router/src/state.dart' as _i2;
import 'package:hello_universe/src/domain/apods_error.dart' as _i11;
import 'package:hello_universe/src/presentation/apods_list/apods_list_cubit.dart'
    as _i8;
import 'package:hello_universe/src/presentation/apods_list/apods_list_data.dart'
    as _i10;
import 'package:hello_universe/src/utils/persistent_cubit_state.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGoRouterState_0 extends _i1.SmartFake implements _i2.GoRouterState {
  _FakeGoRouterState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteConfiguration_1 extends _i1.SmartFake
    implements _i3.RouteConfiguration {
  _FakeRouteConfiguration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackButtonDispatcher_2 extends _i1.SmartFake
    implements _i4.BackButtonDispatcher {
  _FakeBackButtonDispatcher_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouterDelegate_3 extends _i1.SmartFake
    implements _i5.GoRouterDelegate {
  _FakeGoRouterDelegate_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationProvider_4 extends _i1.SmartFake
    implements _i6.GoRouteInformationProvider {
  _FakeGoRouteInformationProvider_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationParser_5 extends _i1.SmartFake
    implements _i7.GoRouteInformationParser {
  _FakeGoRouteInformationParser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApodsListCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodsListCubit extends _i1.Mock implements _i8.ApodsListCubit {
  @override
  _i9.PersistentCubitState<_i10.ApodsListData, _i11.ApodsError> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i12
                .dummyValue<
                  _i9.PersistentCubitState<_i10.ApodsListData, _i11.ApodsError>
                >(this, Invocation.getter(#state)),
            returnValueForMissingStub: _i12
                .dummyValue<
                  _i9.PersistentCubitState<_i10.ApodsListData, _i11.ApodsError>
                >(this, Invocation.getter(#state)),
          )
          as _i9.PersistentCubitState<_i10.ApodsListData, _i11.ApodsError>);

  @override
  _i13.Stream<_i9.PersistentCubitState<_i10.ApodsListData, _i11.ApodsError>>
  get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue:
                _i13.Stream<
                  _i9.PersistentCubitState<_i10.ApodsListData, _i11.ApodsError>
                >.empty(),
            returnValueForMissingStub:
                _i13.Stream<
                  _i9.PersistentCubitState<_i10.ApodsListData, _i11.ApodsError>
                >.empty(),
          )
          as _i13.Stream<
            _i9.PersistentCubitState<_i10.ApodsListData, _i11.ApodsError>
          >);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i13.Future<void> fetchApods() =>
      (super.noSuchMethod(
            Invocation.method(#fetchApods, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void emit(
    _i9.PersistentCubitState<_i10.ApodsListData, _i11.ApodsError>? state,
  ) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(
    _i14.Change<_i9.PersistentCubitState<_i10.ApodsListData, _i11.ApodsError>>?
    change,
  ) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [GoRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouter extends _i1.Mock implements _i15.GoRouter {
  @override
  _i2.GoRouterState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeGoRouterState_0(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeGoRouterState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.GoRouterState);

  @override
  _i3.RouteConfiguration get configuration =>
      (super.noSuchMethod(
            Invocation.getter(#configuration),
            returnValue: _FakeRouteConfiguration_1(
              this,
              Invocation.getter(#configuration),
            ),
            returnValueForMissingStub: _FakeRouteConfiguration_1(
              this,
              Invocation.getter(#configuration),
            ),
          )
          as _i3.RouteConfiguration);

  @override
  _i4.BackButtonDispatcher get backButtonDispatcher =>
      (super.noSuchMethod(
            Invocation.getter(#backButtonDispatcher),
            returnValue: _FakeBackButtonDispatcher_2(
              this,
              Invocation.getter(#backButtonDispatcher),
            ),
            returnValueForMissingStub: _FakeBackButtonDispatcher_2(
              this,
              Invocation.getter(#backButtonDispatcher),
            ),
          )
          as _i4.BackButtonDispatcher);

  @override
  _i5.GoRouterDelegate get routerDelegate =>
      (super.noSuchMethod(
            Invocation.getter(#routerDelegate),
            returnValue: _FakeGoRouterDelegate_3(
              this,
              Invocation.getter(#routerDelegate),
            ),
            returnValueForMissingStub: _FakeGoRouterDelegate_3(
              this,
              Invocation.getter(#routerDelegate),
            ),
          )
          as _i5.GoRouterDelegate);

  @override
  _i6.GoRouteInformationProvider get routeInformationProvider =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationProvider),
            returnValue: _FakeGoRouteInformationProvider_4(
              this,
              Invocation.getter(#routeInformationProvider),
            ),
            returnValueForMissingStub: _FakeGoRouteInformationProvider_4(
              this,
              Invocation.getter(#routeInformationProvider),
            ),
          )
          as _i6.GoRouteInformationProvider);

  @override
  _i7.GoRouteInformationParser get routeInformationParser =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationParser),
            returnValue: _FakeGoRouteInformationParser_5(
              this,
              Invocation.getter(#routeInformationParser),
            ),
            returnValueForMissingStub: _FakeGoRouteInformationParser_5(
              this,
              Invocation.getter(#routeInformationParser),
            ),
          )
          as _i7.GoRouteInformationParser);

  @override
  bool get overridePlatformDefaultLocation =>
      (super.noSuchMethod(
            Invocation.getter(#overridePlatformDefaultLocation),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set configuration(_i3.RouteConfiguration? value) => super.noSuchMethod(
    Invocation.setter(#configuration, value),
    returnValueForMissingStub: null,
  );

  @override
  set routerDelegate(_i5.GoRouterDelegate? value) => super.noSuchMethod(
    Invocation.setter(#routerDelegate, value),
    returnValueForMissingStub: null,
  );

  @override
  set routeInformationProvider(_i6.GoRouteInformationProvider? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationProvider, value),
        returnValueForMissingStub: null,
      );

  @override
  set routeInformationParser(_i7.GoRouteInformationParser? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationParser, value),
        returnValueForMissingStub: null,
      );

  @override
  bool canPop() =>
      (super.noSuchMethod(
            Invocation.method(#canPop, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String namedLocation(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    String? fragment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedLocation,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #fragment: fragment,
              },
            ),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(
                #namedLocation,
                [name],
                {
                  #pathParameters: pathParameters,
                  #queryParameters: queryParameters,
                  #fragment: fragment,
                },
              ),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(
                #namedLocation,
                [name],
                {
                  #pathParameters: pathParameters,
                  #queryParameters: queryParameters,
                  #fragment: fragment,
                },
              ),
            ),
          )
          as String);

  @override
  void go(String? location, {Object? extra}) => super.noSuchMethod(
    Invocation.method(#go, [location], {#extra: extra}),
    returnValueForMissingStub: null,
  );

  @override
  void restore(_i16.RouteMatchList? matchList) => super.noSuchMethod(
    Invocation.method(#restore, [matchList]),
    returnValueForMissingStub: null,
  );

  @override
  void goNamed(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) => super.noSuchMethod(
    Invocation.method(
      #goNamed,
      [name],
      {
        #pathParameters: pathParameters,
        #queryParameters: queryParameters,
        #extra: extra,
        #fragment: fragment,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<T?> push<T extends Object?>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#push, [location], {#extra: extra}),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushReplacement<T extends Object?>(
    String? location, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushReplacement, [location], {#extra: extra}),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushReplacementNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushReplacementNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> replace<T>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#replace, [location], {#extra: extra}),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> replaceNamed<T>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
