// Mocks generated by Mockito 5.4.6 from annotations
// in hello_universe/test/src/domain/fetch_apods_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:hello_universe/src/domain/apods_error.dart' as _i6;
import 'package:hello_universe/src/domain/apods_page_key.dart' as _i2;
import 'package:hello_universe/src/domain/apods_pagination_handler.dart' as _i3;
import 'package:hello_universe/src/domain/apods_repository.dart' as _i4;
import 'package:hello_universe/src/domain/entities/apod.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApodsPageKey_0 extends _i1.SmartFake implements _i2.ApodsPageKey {
  _FakeApodsPageKey_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApodsPaginationHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodsPaginationHandler extends _i1.Mock
    implements _i3.ApodsPaginationHandler {
  MockApodsPaginationHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApodsPageKey nextPageKey(_i2.ApodsPageKey? currentPageKey) =>
      (super.noSuchMethod(
            Invocation.method(#nextPageKey, [currentPageKey]),
            returnValue: _FakeApodsPageKey_0(
              this,
              Invocation.method(#nextPageKey, [currentPageKey]),
            ),
          )
          as _i2.ApodsPageKey);
}

/// A class which mocks [ApodsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodsRepository extends _i1.Mock implements _i4.ApodsRepository {
  MockApodsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TaskEither<_i6.ApodsError, List<_i7.Apod>> fetchApods({
    required String? startDate,
    required String? endDate,
    required bool? includeThumbnails,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchApods, [], {
              #startDate: startDate,
              #endDate: endDate,
              #includeThumbnails: includeThumbnails,
            }),
            returnValue: _i8
                .dummyValue<_i5.TaskEither<_i6.ApodsError, List<_i7.Apod>>>(
                  this,
                  Invocation.method(#fetchApods, [], {
                    #startDate: startDate,
                    #endDate: endDate,
                    #includeThumbnails: includeThumbnails,
                  }),
                ),
          )
          as _i5.TaskEither<_i6.ApodsError, List<_i7.Apod>>);
}
