// Mocks generated by Mockito 5.4.6 from annotations
// in hello_universe/test/src/utils/dependency_injection/injection_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:hello_universe/src/utils/dependency_injection/injector.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [Injector].
///
/// See the documentation for Mockito's code generation for more information.
class MockInjector extends _i1.Mock implements _i2.Injector {
  @override
  T resolve<T extends Object>() =>
      (super.noSuchMethod(
            Invocation.method(#resolve, []),
            returnValue: _i3.dummyValue<T>(
              this,
              Invocation.method(#resolve, []),
            ),
            returnValueForMissingStub: _i3.dummyValue<T>(
              this,
              Invocation.method(#resolve, []),
            ),
          )
          as T);

  @override
  T resolveWithParams<T extends Object, P extends Object?>(P? params) =>
      (super.noSuchMethod(
            Invocation.method(#resolveWithParams, [params]),
            returnValue: _i3.dummyValue<T>(
              this,
              Invocation.method(#resolveWithParams, [params]),
            ),
            returnValueForMissingStub: _i3.dummyValue<T>(
              this,
              Invocation.method(#resolveWithParams, [params]),
            ),
          )
          as T);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
